openapi: 3.0.0
info:
  description: SSO REST API for Cifra app
  title: Cifra SSO REST API
  version: 0.0.1
servers:
- url: /
paths:
  /users/create:
    post:
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
        required: true
      responses:
        "201":
          description: Created
        "409":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Conflict
      summary: Create a new user
components:
  responses:
    conflict:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Conflict
  schemas:
    UserCreate:
      example:
        data:
          attributes:
            username: username
          type: user_create
      properties:
        data:
          $ref: '#/components/schemas/UserCreate_data'
      required:
      - data
      type: object
    UserUpdate:
      properties:
        data:
          $ref: '#/components/schemas/UserUpdate_data'
      required:
      - data
      type: object
    User:
      properties:
        data:
          $ref: '#/components/schemas/User_data'
      required:
      - data
      type: object
    UserCollection:
      properties:
        data:
          $ref: '#/components/schemas/UserCollection_data'
      required:
      - data
      type: object
    Member:
      properties:
        data:
          $ref: '#/components/schemas/Member_data'
      required:
      - data
      type: object
    MemberCreate:
      properties:
        data:
          $ref: '#/components/schemas/MemberCreate_data'
      required:
      - data
      type: object
    MemberUpdate:
      properties:
        data:
          $ref: '#/components/schemas/MemberUpdate_data'
      required:
      - data
      type: object
    Team:
      properties:
        data:
          $ref: '#/components/schemas/Team_data'
      required:
      - data
      type: object
    TeamCreate:
      properties:
        data:
          $ref: '#/components/schemas/TeamCreate_data'
      required:
      - data
      type: object
    TeamUpdate:
      properties:
        data:
          $ref: '#/components/schemas/TeamUpdate_data'
      required:
      - data
      type: object
    Errors:
      description: Standard JSON:API error
      properties:
        errors:
          description: Non empty array of errors occurred during request processing
          items:
            $ref: '#/components/schemas/Errors_errors_inner'
          type: array
      required:
      - errors
      type: object
    UserCreate_data_attributes:
      example:
        username: username
      properties:
        username:
          description: Username
          type: string
      required:
      - username
      type: object
    UserCreate_data:
      example:
        attributes:
          username: username
        type: user_create
      properties:
        type:
          enum:
          - user_create
          type: string
        attributes:
          $ref: '#/components/schemas/UserCreate_data_attributes'
      required:
      - attributes
      - type
      type: object
    UserUpdate_data_attributes:
      properties:
        username:
          description: Username
          type: string
        avatar:
          description: User avatar
          type: string
      required:
      - avatar
      - username
      type: object
    UserUpdate_data:
      properties:
        id:
          description: User ID
          type: string
        type:
          enum:
          - user_update
          type: string
        attributes:
          $ref: '#/components/schemas/UserUpdate_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    User_data_attributes:
      properties:
        username:
          description: Username
          type: string
        role:
          description: User role
          type: string
        avatar:
          description: User avatar
          type: string
        created_at:
          description: User created at
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
      required:
      - avatar
      - created_at
      - role
      - username
      type: object
    User_data:
      properties:
        id:
          description: User ID
          type: string
        type:
          enum:
          - user
          type: string
        attributes:
          $ref: '#/components/schemas/User_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    UserCollection_data_attributes:
      properties:
        users:
          items:
            $ref: '#/components/schemas/User_data_attributes'
          type: array
      required:
      - users
      type: object
    UserCollection_data:
      properties:
        type:
          enum:
          - user_collection
          type: string
        attributes:
          $ref: '#/components/schemas/UserCollection_data_attributes'
      required:
      - attributes
      - type
      type: object
    Member_data_attributes:
      properties:
        userId:
          description: User ID
          type: string
        role:
          description: User role
          type: string
        description:
          description: Description
          type: string
        created_at:
          description: User created at
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
      required:
      - created_at
      - description
      - role
      - userId
      type: object
    Member_data:
      properties:
        id:
          description: Employee ID
          type: string
        type:
          enum:
          - member
          type: string
        attributes:
          $ref: '#/components/schemas/Member_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    MemberCreate_data_attributes:
      properties:
        userId:
          description: User ID
          type: string
        role:
          description: User role
          type: string
        description:
          description: Description
          type: string
      required:
      - description
      - role
      - userId
      type: object
    MemberCreate_data:
      properties:
        type:
          enum:
          - member_create
          type: string
        attributes:
          $ref: '#/components/schemas/MemberCreate_data_attributes'
      required:
      - attributes
      - type
      type: object
    MemberUpdate_data_attributes:
      properties:
        role:
          description: User role
          type: string
        description:
          description: Description
          type: string
      required:
      - description
      - role
      type: object
    MemberUpdate_data:
      properties:
        type:
          enum:
          - member_update
          type: string
        attributes:
          $ref: '#/components/schemas/MemberUpdate_data_attributes'
      required:
      - attributes
      - type
      type: object
    Team_data_attributes:
      properties:
        name:
          description: Team name
          type: string
        description:
          description: Team description
          type: string
        members:
          items:
            $ref: '#/components/schemas/Member_data_attributes'
          type: array
        created_at:
          description: Team created at
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
      required:
      - created_at
      - description
      - members
      - name
      type: object
    Team_data:
      properties:
        id:
          description: Team ID
          type: string
        type:
          enum:
          - team
          type: string
        attributes:
          $ref: '#/components/schemas/Team_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    TeamCreate_data_attributes:
      properties:
        name:
          description: Team name
          type: string
        description:
          description: Team description
          type: string
      required:
      - description
      - name
      type: object
    TeamCreate_data:
      properties:
        type:
          enum:
          - team_create
          type: string
        attributes:
          $ref: '#/components/schemas/TeamCreate_data_attributes'
      required:
      - attributes
      - type
      type: object
    TeamUpdate_data:
      properties:
        id:
          description: Team ID
          type: string
        type:
          enum:
          - team_update
          type: string
        attributes:
          $ref: '#/components/schemas/TeamCreate_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    Errors_errors_inner:
      properties:
        title:
          description: "Title is a short, human-readable summary of the problem"
          example: Bad Request
          type: string
        detail:
          description: Detail is a human-readable explanation specific to this occurrence
            of the problem
          example: Request body was expected
          type: string
        status:
          description: Status is the HTTP status code applicable to this problem
          enum:
          - 400
          - 401
          - 403
          - 404
          - 409
          - 500
          example: 400
          type: integer
      required:
      - status
      - title
      type: object
