openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra app
  version: 0.0.1

paths:
  /users/create:
    post:
      summary: Create a new user
      operationId: createUser
      responses:
        '201':
          description: Created

components:
  schemas:
    User:
      $ref: './spec/components/schemas/User.yaml'
    UserUpdate:
      $ref: './spec/components/schemas/UserUpdate.yaml'
    UserCollection:
      $ref: './spec/components/schemas/UserCollection.yaml'
    Member:
      $ref: './spec/components/schemas/Member.yaml'
    MemberCreate:
      $ref: './spec/components/schemas/MemberCreate.yaml'
    MemberUpdate:
      $ref: './spec/components/schemas/MemberUpdate.yaml'
    Team:
      $ref: './spec/components/schemas/Team.yaml'
    TeamCreate:
      $ref: './spec/components/schemas/TeamCreate.yaml'
    TeamUpdate:
      $ref: './spec/components/schemas/TeamUpdate.yaml'